### ISSUE TITLE
Cards Design Component

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#113]
We currently have cards in a few locations on our website: the [Signup Flow](https://keep.id/signup-branch), the [Our Team page](https://keep.id/our-team), the [Admin Dashboard](https://www.figma.com/file/sgasGqleY3aA8jBSQcaKM8/Admin-Dashboard?node-id=108%3A76), the [Client Dashboard](https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard?node-id=70%3A870), and the [Find Organizations page](https://www.figma.com/file/7GXv80XxYvbHeHvMNz3HPB/Find-Organizations?node-id=5%3A636). (Some of these designs have not been fully implemented yet.) 

Here are some past component redesigns we've done: 
- Tables: [Research summary](https://docs.google.com/document/d/1Dr74--9MYiIesE4ENfl5v9sWc_LWmdbY-28NuUQ5un0/edit?usp=sharing) + [Figma file](https://www.figma.com/file/0ZahIADAc8HwkI55P8IKlU/Tables?node-id=0%3A1)
- Notifications + Alerts: [Research summary](https://docs.google.com/document/d/1-QO8I7q1EiubnHk0A_n5i6YgTg2rUmc6clRZRi8WS_g/edit?usp=sharing) + [Figma file](https://www.figma.com/file/bzp24t4NEgovQ6RkovMMnr/Notifications?node-id=5%3A97).

We would like to have a new card design that we can use consistently throughout our site. We also want to make sure that we define what the card design should look for different use cases (i.e. cards with pictures, cards with links, cards that appear in search results (like on the Find Organizations page), cards on different screen sizes). 

**Research Component**

To start off, it would be good to do some research into what best practices look like for UI/UX card design. Specifically, it would be good to answer:
- What are the use cases for cards on a website?
- Why are cards important?
- What are some best practices for the UI and UX of the card?

Good sites for UI/UX research include [Nielsen Norman Group](nngroup.com), [UX Planet](uxplanet.org), [UX Collective ](uxdesign.cc), and [Toptal](https://www.toptal.com/designers/blog).

**Visual Design Component**

Our current cards seem a bit unsubstantial: maybe increasing line weight or (if we do bios later on) adding a drop shadow? We currently have cards on our Team page and in our Signup flow. 

Some examples of useful cards:

https://polaris.shopify.com/components/structure/card#navigation 
https://blueprintjs.com/docs/#core/components/card 
https://material.io/components/cards

If possible, please include examples of cards that also highlight when hovered, as well as the proper elevation (or lack thereof).
Also, include cards that have a picture and without picture, with title and without title, etc. In general, map out the anatomy of the card, similar to this: 
![image](https://user-images.githubusercontent.com/13875633/97389538-e75eea00-18b0-11eb-8595-2f77faad35c4.png)
What about expandability of cards? Some other things to think about...

Also, define rules of usage (I think material design does this really well)

**Comment by mishyi** [comment]
https://www.figma.com/file/m0pQ7jz59b5D8K9ErwfCu2/Cards?node-id=0%3A1

**Comment by scye09** [comment]
All card components across the Figma designs should have been updated (see Sign up Flows, Client Dashboard, Admin Dashboard) - Michelle's design should be ready for implementation now @crchong1
