### ISSUE TITLE
Search Bar Design Component

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#114]
We currently have search bars in a few locations on our website: the [My Documents](https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard?node-id=70%3A870) page, the My Applications page, the [Admin Panel](https://www.figma.com/file/PpjMYAJWjnZBmYlx71jHah/Admin-Panel?node-id=0%3A1) page, the Worker Panel, and the [Find Organizations](https://www.figma.com/file/7GXv80XxYvbHeHvMNz3HPB/Find-Organizations?node-id=5%3A636) page. (Many of these designs have not been fully implemented yet.)

Here are some past component redesigns we've done:

Tables: [Research summary](https://docs.google.com/document/d/1Dr74--9MYiIesE4ENfl5v9sWc_LWmdbY-28NuUQ5un0/edit) + [Figma file](https://www.figma.com/file/0ZahIADAc8HwkI55P8IKlU/Tables?node-id=0%3A1)
Notifications + Alerts: [Research summary](https://docs.google.com/document/d/1-QO8I7q1EiubnHk0A_n5i6YgTg2rUmc6clRZRi8WS_g/edit) + [Figma file](https://www.figma.com/file/bzp24t4NEgovQ6RkovMMnr/Notifications?node-id=5%3A97).

We would like to have a new search bar design that we can use consistently throughout our site. We also want to make sure that we define what the search bar design should look for different use cases and behavior (i.e. resizing, autocomplete, instant search, advanced search options, etc.).

**Research Component**

To start off, it would be good to do some research into what best practices look like for UI/UX card design. Specifically, it would be good to answer:

- What are the use cases for search bars on a website?
- Why are search bars important?
- What are some best practices for the UI and UX of the search bar?

Good sites for UI/UX research include [Nielsen Norman Group](nngroup.com), [UX Planet](uxplanet.org), [UX Collective](uxdesign.cc), and [Toptal](https://www.toptal.com/designers/blog).

**Visual Design Component**

Once you have compiled some research into best practices, create some mockups of search bars while documenting what search bars would look like at different screen sizes, hover / click states, margins / padding, etc.

**Comment by scye09** [comment]
@chels20 could you link your Figma file here? then we can go through the [Final Design Checklist](https://docs.google.com/document/d/1W4uAktJIXLgThgCVJGwhHN81qaezVy5Ch-l4pR-ATL8/edit) and approve it (with a react) if it's ready for implementation

**Comment by scye09** [comment]
@leonna26 @mishyi here is Chelsea's search bar design for final review! https://www.figma.com/file/cALrYCkp6tSEDkA8v0q2rR/Search-Bar

**Comment by scye09** [comment]
@chels20 thanks for sharing your Figma file - I hope your Figma issue is resolved now! I left some comments, let me know if you have any questions :) do you think you could make those changes by tomorrow or Tuesday's meeting?
