### ISSUE TITLE
File Input Design Component

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#115]
In the View & Prints Document page of the client workflow, the "Upload" button looks awkward. We could have a better UX/UI for the upload files process. 

We need to standardize behavior of our file inputs. This includes an option for multiple uploads as well. 
Some good examples: 
https://blueprintjs.com/docs/#core/components/file-input 

Some things to think about:
Should we have a drag an drop area?
How do we show multiple uploads? 
What about file previews? 
How do we indicate the required file types?

We should decide on the design of the upload button before and after uploading files. How do we let the user know what files and how many have been uploaded? Also, do we need a Choose Files button?

**Comment by scye09** [comment]
See #114 for examples of other component redesigns and a description of what to research + good sources for UI/UX principles.

**Comment by mishyi** [comment]
@scye09 @chels20 @leonna26 
Finished file input: https://www.figma.com/file/wEcxCn7GMB0c3ftYNW4xsM/File-Input?node-id=0%3A1

**Comment by scye09** [comment]
Awesome work and very thorough user flow @mishyi! I think this is ready for implementation @crchong1
