### ISSUE TITLE
Update table and pagination design

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#122]
Table and pagination component design has been redesigned - this needs to updated in all pages that contain tables and pagination.

Figma file: https://www.figma.com/file/0ZahIADAc8HwkI55P8IKlU/Tables

**Comment by scye09** [comment]
Updated the tables in the [Worker Signup Flow](https://www.figma.com/file/uUjqsTv6UJrld51CJ42mJ6/Worker-Signup-Flow?node-id=404%3A652) and the [Admin Panel](https://www.figma.com/file/PpjMYAJWjnZBmYlx71jHah/Admin-Panel?node-id=3%3A563) Figma designs.

**Comment by scye09** [comment]
@leonna26 could you update the table on the My Applications page?

**Comment by leonna26** [comment]
@scye09 - wanna give a final design review? https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard?node-id=70%3A870

**Comment by scye09** [comment]
@leonna26 sure! the new table looks good, just a few things:
- Could you add icons to the Download, Print, and Delete buttons? It would be good for users to associate icons with certain actions

**Comment by scye09** [comment]
@leonna26 Also I'm starting to think the icons are kind of small and it might be a bit inconsistent to have some icons without any accompanying action (i.e. View, Download, Print). Thoughts on maybe having a column for View with the view icon (since this is the most common action) + another column with a "More Actions" dropdown where they can access all of the other actions?

**Comment by scye09** [comment]
@mishyi feel free to take a look as well!

**Comment by leonna26** [comment]
This should be ready for another review! https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard?node-id=70%3A870

**Comment by scye09** [comment]
Looks good! I made a few minor changes in spacing but I think we're done with this for now :)
