### ISSUE TITLE
ApplicationForm bugs: Continue and Submit buttons (unintuitive), pages are always 0

### ISSUE THREAD

**Issue by vanessa-hu** [keepid/keepid_client#129]
- always says Page 0 out of 0; figure out how to break into separate pages + render accordingly
- on the only (or last) page, there's a continue AND a submit button which doesn't make sense; take away continue if that is the case

**Comment by vanessa-hu** [comment]
related to #81: 
- Page numbers don't change when moving on to next page
- "Previous step" button should not be on the first page
- Get rid of "Submit Form Answers" button - users should click "Continue" button instead

**Comment by loafyyy** [comment]
@steffen12 did you work on this?

**Comment by vanessa-hu** [comment]
pr #177 should address this & #81
