### ISSUE TITLE
Table Edit and Delete and Save Column Toggling

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#133]
Have the ability to add an edit and delete col to a table if needed, or else the edit and delete col will be hidden

**Comment by vanessa-hu** [comment]
canModify boolean prop to table! also misread this at first and added a thing where certain cols can't be edited (ex: can't change id numbers but can change other info in a row) so that's a cantEditCols prop (a set of col indices for data you can't edit)

**Comment by vanessa-hu** [comment]
maybe I will modify that to be set of col names..
