### ISSUE TITLE
Table Text and Spacing Styling (found under general guidelines)

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#134]

**Comment by vanessa-hu** [comment]
* [column widths](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/226)
* [other link](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Header%20Columns&selectedStory=Customize%20Column%20Style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
