### ISSUE TITLE
Table Adding checkbox

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#140]

**Comment by vanessa-hu** [comment]
- have to make object and pass to Bootstrap Table as selectRow prop
- examples of many possible fields
```
const selectRow = {
  mode: 'checkbox',
  clickToSelect: true,
hideSelectAll: true,
  bgColor: '#00BFFF', //of the selected rows
  //classes: 'someClass', OR function
  classes: (row, rowIndex) =>
    (rowIndex > 1 ? 'row-index-bigger-than-2101' : 'row-index-small-than-2101'),
  onSelect: (row, isSelect, rowIndex, e) => {
    console.log(row.id);
    console.log(isSelect);
    console.log(rowIndex);
    console.log(e);
  },
  onSelectAll: (isSelect, rows, e) => {
    console.log(isSelect);
    console.log(rows);
    console.log(e); // 
  }
};
```
* if write as sep function [don't need e??](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
* based on table design, can select all box, bgColor should be lavender #E8E9FF #141 , #142 likely solved by adding a set state to the onSelect thing?
* to finish later: seems a bit hard to custom style the checkbox :( [custom checkbox](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1290)
