### ISSUE TITLE
Table x results per page functionality and styling

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#144]
bottom bar

**Comment by vanessa-hu** [comment]
built in standalone, that works easily enough:
```
      <PaginationTotalStandalone
       {...paginationProps}
        />
```

in paginationOption,
        const paginationOption = {
            custom: true,
            totalSize: data.length,
            paginationTotalRenderer: customTotal,
            page: currentPage, 
            pageStartIndex: 0,
            sizePerPage: itemsPerPage, 
        };
where we customize this result:
```
        const customTotal = (from, to, size) => (
            <span className="react-bootstrap-table-pagination-total">
              Showing { from }-{ to } of { size } Results
            </span>
        );
```
