### ISSUE TITLE
Add back button to top of View Application page

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#166]
![image](https://user-images.githubusercontent.com/28871950/100288338-7446a300-2f44-11eb-8165-6d2c3f65b98f.png)

Steps to Reproduce: log in as client -> click "My Applications" -> Click "View Application"

Issue: There is no back button at the top of the View Application page - this is especially troublesome for longer forms where you have to scroll for a very long time until you can reach the back button at the bottom of the page

Resolve by: for now, moving the back button from the bottom left to the top left corner of the page (above the progress bar). @leonna26 could we update the design to account for this problem?

**Comment by loafyyy** [comment]
Fixed with #174.
