### ISSUE TITLE
User is redirected to Client Landing Page upon submission

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#167]
Steps to reproduce: log in as client -> click "My Applications" -> Click "View Application" -> Submit application

Issue: Upon submission of application, user is redirected to Client Landing Page instead of My Applications page. This is very jarring and the user has to click on My Applications again to confirm that their application has been submitted.

Resolve by: Redirect user to My Applications page after submission.

**Comment by ankitaksethi** [comment]
In ApplicationForm.tsx , under if(submitSuccessful) change return ( Redirect to="/home" ) to ( Redirect to="/applications" )
<img width="507" alt="Screen Shot 2021-01-14 at 4 38 33 PM" src="https://user-images.githubusercontent.com/25338020/104583537-41d53e80-5687-11eb-86d8-e20b99a1956c.png">
<img width="507" alt="Screen Shot 2021-01-14 at 4 38 20 PM" src="https://user-images.githubusercontent.com/25338020/104583546-44379880-5687-11eb-8b8b-a74adc8315b8.png">
