### ISSUE TITLE
Application status is not updated

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#169]
Steps to reproduce: log in as client -> click "My Applications"

Issue: Upon submission of application, the Status column on this page is not updated, so the user has no way of knowing that their application has been successfully submitted. 

Resolve by: updating Status column. Status should be explicit - for example, "Pending Approval", "Approved", "Rejected".

**Comment by loafyyy** [comment]
@crchong1 I'm looking at the /get-documents route, and I don't think there is a status column/we don't have this information.

**Comment by crchong1** [comment]
we dont have a status column it seems..... yeah that something i can ask the backend to work on. this might take like a couple weeks though

**Comment by loafyyy** [comment]
Closing this issue. Not sure how we can get the status of an application...
