### ISSUE TITLE
KEEP-ID-DEVELOPER account Re-Upload document failure

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#173]
![image](https://user-images.githubusercontent.com/65623389/100527112-5e7fea80-319d-11eb-9de0-e37fa9e9be14.png)

Sometimes when you log back in as Client the wrong document was uploaded or no document was uploaded.

**Comment by loafyyy** [comment]
@JohnBaek-wr Can you specify what you did to cause this error?

**Comment by loafyyy** [comment]
Added error handling in #174 .

**Comment by loafyyy** [comment]
Fixed with #174.
