### ISSUE TITLE
Unable to Fill in anything (although progress bar rises when you "type" in something)

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#182]
![image](https://user-images.githubusercontent.com/65623389/101217898-1d318400-3650-11eb-8387-0f0e35a5cec8.png)

Chelsea had similar issue when filling out onboarding form through keep.id.

**Comment by loafyyy** [comment]
Assigning @steffen12 to this because I'm pretty sure he worked on the Applications.
