### ISSUE TITLE
search results for find organizations

### ISSUE THREAD

**Issue by leonna26** [keepid/keepid_client#193]
i notice that search results for the find organizations page is in km instead of mi. is this something we can fix? 
<img width="1297" alt="Screen Shot 2020-12-14 at 11 27 36 AM" src="https://user-images.githubusercontent.com/55723857/102107150-67102c00-3dff-11eb-87c1-73076dee90b7.png">

**Comment by crchong1** [comment]
I dont think so actually- km is fine for now i guess...
