### ISSUE TITLE
Admin account → My Clients design

### ISSUE THREAD

**Issue by dglaser2** [keepid/keepid_client#218]
Colors of buttons under Client Actions perhaps should be the same, as the various colors (especially green and red) can be misleading.

Positioning of objects under "My Clients" header is confusing. For example, Signup Worker button doesn't really have anything to do with "My Clients". Shouldn't Signup Worker be on Admin Panel page? 
Can objects under "My Clients" header be organized more neatly?

Drop down menu should hide and apply selection to page (perhaps reload page if needed) after making choice under # Items per page.

Side note: spacing between page header and top menu bar should be consistent between My Clients and Admin Panel pages.

**Comment by leonna26** [comment]
hi David I think these concerns have been addressed with the Figma designs we have, they're just not reflected on our site yet. feel free to look over our Figma files and follow up or close this issue if you think we're all good :)

**Comment by dglaser2** [comment]
yes agreed! thanks :)
