### ISSUE TITLE
Use new card components for client dashboard

### ISSUE THREAD

**Issue by gkang2018** [keepid/keepid_client#233]
If already created, we want to use these card components with the background shadows for the client dashboard. If not, modify what exists to mimic this look. 
<img width="1031" alt="Screen Shot 2021-01-23 at 4 41 23 PM" src="https://user-images.githubusercontent.com/46234727/105614814-d92e4600-5d99-11eb-8bd2-5c2b759e8197.png">

**Comment by leonna26** [comment]
minor note but illustrations were changed for the cards here. thank you! https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard
