### ISSUE TITLE
February 10 internal test

### ISSUE THREAD

**Issue by dglaser2** [keepid/keepid_client#247]
Admin account:
- Allowed to continue without adding an organization website, but upon trying to sign up I get the following error:
Server Failure: SyntaxError: The string did not match the expected pattern
- Upon filling in an organization website, I am not able to sign up and get a blank error message
- Loading indicator upon pressing submit in client sign up? (Long load time)
- Admin panel crashes

Worker account:
- Unable to access client info... nothing happens after entering their login credentials to view a doc

Client account:
- Unable to login:
Error: Network Failure: Check Server Connection.

Developer account:
Same as client account

**Comment by crchong1** [comment]
@gkang2018 can you look into the organization website sign up problems?

**Comment by crchong1** [comment]
@xander-cernek can you look into the admin panel crashes?

**Comment by crchong1** [comment]
@nrod80 can you look into the login issues?

**Comment by xander-cernek** [comment]
Closed my issue ^_^ will be good on the next deploy

**Comment by nrod80** [comment]
@dglaser2 Have the client/developer login issues persisted? I was not able to reproduce in production

**Comment by dglaser2** [comment]
@nrod80 nope! that seems to be working now
