### ISSUE TITLE
EULA Verification

### ISSUE THREAD

**Issue by dglaser2** [keepid/keepid_client#259]
When creating an account, since clicking to edit information at point of verification (before submitting & signing up) requires that you sign EULA once again, perhaps user should sign EULA after verification

**Comment by gkang2018** [comment]
i made the change so that when you click back to edit the information or go back a page, the signature should persist

**Comment by dglaser2** [comment]
> i made the change so that when you click back to edit the information or go back a page, the signature should persist

awesome thanks!
