### ISSUE TITLE
Username validator in organization signup doesn't work

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_client#27]
The validator always returns true - check out the method I had written in the userController.java which tells you whether a username is taken or not

**Comment by steffen12** [comment]
EIN Validator also doesn't work. 
Might be good to double check all the validators work.

**Comment by steffen12** [comment]
Password validator too

**Comment by crchong1** [comment]
your existing validator function actually doesn't work anymore with the way we are validating fields on the front end, but yes we will make another validation function to check if username and organization names are taken
