### ISSUE TITLE
Pressing Enter on Client Search as worker redirects to the Keep.id homepage.

### ISSUE THREAD

**Issue by jonathanxuexue** [keepid/keepid_client#30]
![Screen Recording 2020-09-16 at 11 32 35 AM](https://user-images.githubusercontent.com/59134039/93380666-62de6d80-f814-11ea-94dd-2cfd31613384.gif)

If you press enter on the textfield for searching clients as a worker, you are redirected to the Keep.id homepage.

**Comment by crchong1** [comment]
@MelindaCardenas maybe you could look into this?
