### ISSUE TITLE
Margin on success alert is off

### ISSUE THREAD

**Issue by jonathanxuexue** [keepid/keepid_client#31]
<img width="1186" alt="Screen Shot 2020-09-16 at 12 03 15 PM" src="https://user-images.githubusercontent.com/59134039/93380845-a638dc00-f814-11ea-886d-8290ad03a90c.png">

There's a bottom margin of 1em - should be 0.

**Comment by jonathanxuexue** [comment]
Also top margin for the whole box is too small – it should be 16px - 1em?

**Comment by crchong1** [comment]
@scye09 do you think you could take a quick look?
