### ISSUE TITLE
Text in sign up flow is broken

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#36]
![image](https://user-images.githubusercontent.com/13875633/93634900-5a766600-f9bf-11ea-93c7-6dbd2af74d4a.png)

You will be the 1 of your organization. As the 1,
you can set up accounts for
other workers in the organization and for your clients.

This needs to be better explained. What is a 1? I think you mean admin, but it would be better to talk about what exactly the admin does other than set up accounts for other workers in the organization

Maybe @scye09 and @MelindaCardenas you two could talk more about what would be a better description?

**Comment by scye09** [comment]
Hmm so we were thinking something like: 
You will be the admin of your organization. As the admin, you can:
- Set up accounts for clients and other workers in the organization
- Manage account permissions and roles for all members within your organization
- Sign documents and manage client applications

Is there anything else an admin can do that other roles can't?

**Comment by crchong1** [comment]
i think thats a good description
