### ISSUE TITLE
Adding an "Other" Option to client document uploads

### ISSUE THREAD

**Issue by danielsjoo** [keepid/keepid_client#377]
When a client uploads a document, he is limited to “Drivers License”, “Social Security Card”, “Birth Certificate”, and “Vaccine Card”. I believe there should be an “Other” as well since people use all kinds of things for id, like old bills, veteran cards, passport cards, or proof of former employment. (I think it might require backend implementation). But also, you can’t even see this property in the table.

![image](https://user-images.githubusercontent.com/68679808/174899885-062c00bd-bd46-48a6-8e5b-55a2489bbab9.png)

**Comment by mkhagan8** [comment]
@nng9 What's the status on this? Needs to be done by the end of the day

**Comment by lizyn** [comment]
ID Options to Add:
Medicaid Card
Veteran ID Card
Other

**Comment by lizyn** [comment]
no backend changes needed before we add an "identification category" field in the database.
