### ISSUE TITLE
Report an Issue does not successfully submit issues

### ISSUE THREAD

**Issue by danielsjoo** [keepid/keepid_client#396]
Clicking submit on the report an issue page after filling fields produces error. Fixing this might involve backend.

<img width="1440" alt="Screen Shot 2022-07-07 at 6 37 57 PM" src="https://user-images.githubusercontent.com/68679808/178631377-c2b81fb6-c38d-437a-a5ad-a1f165f60e7b.png">

**Comment by lizyn** [comment]
can successfully report issues with emails, closed.

**Comment by mkhagan8** [comment]
![BugStillNotFixed-JulyFourteenth](https://user-images.githubusercontent.com/109312540/179075943-f5b34d73-d404-4bb9-ae82-11c1390b5a5b.PNG)

We need to reopen this issue, I just tried it and it's not working. @danielsjoo @lizyn @crchong1

**Comment by mkhagan8** [comment]
https://user-images.githubusercontent.com/109312540/179077337-2f4b7f66-e92e-4555-972b-a2dde82244b0.mp4

Here's a video
