### ISSUE TITLE
Forgot Password feature does not work

### ISSUE THREAD

**Issue by danielsjoo** [keepid/keepid_client#399]
Entering a valid username into this screen returns a server error.

<img width="1440" alt="Screen Shot 2022-07-08 at 5 55 15 PM (1)" src="https://user-images.githubusercontent.com/68679808/178697301-4de70649-fdb2-49ab-b47c-f75b4b388b3e.png">

**Comment by mkhagan8** [comment]
This needs to be reopened, just tried it and it doesn't work. Here's a video:

https://user-images.githubusercontent.com/109312540/179078014-96c633a4-950b-482d-922a-ec1f7e27685e.mp4

**Comment by lizyn** [comment]
@mkhagan8 Hey Michael, can you test it again?
