### ISSUE TITLE
Report an Issue redesign

### ISSUE THREAD

**Issue by leonna26** [keepid/keepid_client#43]
Figma file here https://www.figma.com/file/NDdvgUHMiFgz2eRvdevNnE/Report-An-Issue?node-id=0%3A1
* Change footer of site to be "Report an Issue" instead of "Report a Bug"

**Comment by crchong1** [comment]
@vanessa-hu this basically is a small page redesign. It shouldn't be too complicated, but wanted to get your hands a bit wet before diving into larger page redesigns. 

When you are finished with the code, please schedule a call with @leonna26 just for a quick design review to make sure that the design matches what she had in mind.

**Comment by vanessa-hu** [comment]
First pass linked in PR request here! https://github.com/keepid/keepid_client/pull/60
