### ISSUE TITLE
Keep.id Banner & My Client Page

### ISSUE THREAD

**Issue by mkhagan8** [keepid/keepid_client#457]
**Describe the bug**
It seems unintentionally the banner at the top of the website has been altered. Let's revert it back to how it was (see screenshots below).

The My Clients, My Organization, and Home on the Client login is scrunched up. This should be fixed.

**Screenshots**
Before (Correct): 
<img width="1280" alt="Screen Shot 2022-09-21 at 11 24 43 AM" src="https://user-images.githubusercontent.com/109312540/193159125-49d135ad-c273-4be5-9cae-0018ef7b07fc.png">
 After (Incorrect):
![Screen Shot 2022-09-29 at 6 00 38 PM](https://user-images.githubusercontent.com/109312540/193159154-d64024f0-899b-448d-a01e-9e745c0b61c6.png)

Other Screens:
<img width="1392" alt="Screen Shot 2022-10-02 at 8 31 10 PM" src="https://user-images.githubusercontent.com/109312540/193483431-8ba5133f-1371-415c-bb83-5b2b567efacf.png">
<img width="1392" alt="Screen Shot 2022-10-02 at 8 31 56 PM" src="https://user-images.githubusercontent.com/109312540/193483458-c89d9738-a8d1-48d0-be52-2f869b75dd4e.png">
<img width="1392" alt="Screen Shot 2022-10-02 at 8 33 08 PM" src="https://user-images.githubusercontent.com/109312540/193483506-c26f632b-3753-4d56-8357-aeb14f673c16.png">

**Comment by crchong1** [comment]
fixed
