### ISSUE TITLE
Clicking "client profile" as worker/admin redirects to homepage

### ISSUE THREAD

**Issue by crisptofuring** [keepid/keepid_client#46]
![Screenshot (9)](https://user-images.githubusercontent.com/5490025/94513827-b75af300-01ed-11eb-92d4-d0e3c320f84e.png)
This button just goes back to the keepid homepage for some reason? It also immediately logs out the current user.

**Comment by crchong1** [comment]
this is because the client profile page hasn't been finished yet, sadly. I will link melinda

**Comment by MelindaCardenas** [comment]
Client Profile Page now available! Closing issue.
