### ISSUE TITLE
Client Quick Access Flow

### ISSUE THREAD

**Issue by mkhagan8** [keepid/keepid_client#460]
**Describe the bug**
When a client selects an ID to be assigned to any of the Quick Access IDs, the site doesn't save their selection. Nothing shows up, this needs to be fixed 

**To Reproduce**
1. Go to the Client Landing Page
2. Select one of the Quick Access IDs and press Set Default ID button
3. Select a document 

**Expected behavior**
No Quick Access ID will be shown even after selecting one

**Screenshots**
<img width="1392" alt="Screen Shot 2022-10-06 at 4 31 46 PM" src="https://user-images.githubusercontent.com/109312540/194412799-41a8acf8-69a4-48e3-ba6c-298acc289828.png">

**Additional context**

**Comment by crchong1** [comment]
this is fixed
