### ISSUE TITLE
LOGGED IN AS ADMIN - Changing Permissions of Workers at Nonprofit

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#50]
![image](https://user-images.githubusercontent.com/65623389/94630741-9ac5c600-0294-11eb-8e64-c8b7c9d17713.png)

Organization is White Council, I am Gandalf Grey, who is an Admin. I have a worker, Peregrin Took, and I try to set permissions to Admin as well so that he can see our clients' documents. See that "Save Changes" feature is coming soon. OK, but this also means that right now nonprofit organizations beta testing cannot change their workers' viewing permissions and neither their own viewing permissions (I can also not change my own permission to Worker).

**Comment by crchong1** [comment]
We will work on this

**Comment by crchong1** [comment]
we have removed this page for now

**Comment by JohnBaek-wr** [comment]
Got it
