### ISSUE TITLE
LOGGED IN AS ADMIN AND CLIENT - Unable to Search Documents/Applications

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#51]
I select "View Applications" from Admin Panel. Some time ago I uploaded a PDF copy of _A Storm of Swords_ (not the same world, I know, but). So I search "storm" and the 404 page appears.

![image](https://user-images.githubusercontent.com/65623389/94631066-728a9700-0295-11eb-951a-977a83bdd26f.png)

When I'm logged in as Client (e.g. Wormtongue), I can see the three documents that were uploaded, but still can't search (searching "storm" leads to 404).

**Comment by crchong1** [comment]
I think all the view application stuff is @steffen12 's, but i do not know how he is going to fix that
