### ISSUE TITLE
LOGGED IN AS ADMIN - Failure to Send Email Invite for Joining Organization

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#54]
![image](https://user-images.githubusercontent.com/65623389/94736338-1463bf80-033a-11eb-9ea4-e95e04cbb464.png)

I know a mortal named John and I'd like to invite him to White Council as a Worker. I sent him an email invite, or tried to. A strange message joined the fray.

**Comment by crchong1** [comment]
@MelindaCardenas can you look into this?

**Comment by MelindaCardenas** [comment]
Issue (hopefully) fixed a few months ago -- let me know if you ever see this issue pop up again though.

**Comment by MelindaCardenas** [comment]
Issue (hopefully) fixed a few months ago -- let me know if you ever see this issue pop up again though.
