### ISSUE TITLE
LOGGED IN AS ADMIN AND CLIENT - I am logged out when I hit Log Out

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#57]
![image](https://user-images.githubusercontent.com/65623389/94737302-a1f3df00-033b-11eb-9600-95abf0e35f4a.png)

Sounds tautological, but rather than be properly logged out, this large "404" appears. I know no 404, not even in my days making music for Ilúvatar.

The same applies for when I am logged in as Client (Wormtongue).

**Comment by crchong1** [comment]
we are already looking into this issue
