### ISSUE TITLE
CLIENT - send email leads to 404

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#61]
Logged in as Wormtongue, I tried sending an email to jcbaek314@gmail.com. It led to the big 404.

**Comment by crchong1** [comment]
send email doesn't work i dont think

**Comment by crchong1** [comment]
we will include that functionality later. Can you include a screenshot of where that send email button is? We should remove that link

**Comment by JohnBaek-wr** [comment]
![image](https://user-images.githubusercontent.com/65623389/95259893-dfea7a80-07f5-11eb-9f63-c74ff59684b5.png)
First here, then:
![image](https://user-images.githubusercontent.com/65623389/95259924-e842b580-07f5-11eb-8088-807951f0aa62.png)

**Comment by crchong1** [comment]
ah yes this part will all be removed.... soon i think？
