### ISSUE TITLE
Find Organization Page needs better padding, and there is a table bug

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#62]
![image](https://user-images.githubusercontent.com/13875633/95275816-898e3380-0817-11eb-9830-a7caf410eb97.png)

There is strange purple bar on the right hand side. In addition, I think the padding numbers can be tweaked so that the page doesn't look as cramped.

**Comment by loafyyy** [comment]
I don't think this is the Find Organizations (https://keep.id/find-organizations) page?
