### ISSUE TITLE
JSON Communication

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_client#64]
Right now, we need to make everything communicate using JSON - it is actually pretty messed up right now.

On the server, we use a mix of ctx.json and ctx.result
And even within ctx.json, sometimes we are sending a string, and sometimes JSON object

On the client, we use JSON.parse() and result => result.json(), while we should not use JSON.parse at all

We need to standardize this

**Comment by crchong1** [comment]
@steffen12 i already changed all of this with the refactor- we should only use ctx.result(string) and the front end should never use JSON.parse

**Comment by crchong1** [comment]
you have old versions of the code
