### ISSUE TITLE
Redesign admin panel

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#66]
Redesigned the admin panel to be more simple and especially simplified the CRUD process.

Figma file: https://www.figma.com/file/PpjMYAJWjnZBmYlx71jHah/Admin-Panel

**Comment by crchong1** [comment]
hey @joeyszhao do you want to work on this new admin panel?

**Comment by scye09** [comment]
@joeyszhao just an FYI, I just changed the alert message design in the Admin Panel design

**Comment by scye09** [comment]
Updated the admin panel design with new table design - also changed the columns to be more inline with the [worker signup flow design](https://www.figma.com/file/uUjqsTv6UJrld51CJ42mJ6/Worker-Signup-Flow?node-id=404%3A652).

**Comment by crchong1** [comment]
closing this
