### ISSUE TITLE
Take out Birth Date

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_client#67]
Let us not ask workers (admin, workers) what their birth date is in signuo

**Comment by steffen12** [comment]
Actually, let's reduce the amount of information we need to ask of from the workers/admins. Let's have a talk to discuss this. For example, we should still ask for their personal phone and personal email (in case they need to be contacted directly) but not their personal address or birth date - only clients should be asked this

**Comment by crchong1** [comment]
i think its fine to leave in for now, tbh. Its not a real hinderance

**Comment by crchong1** [comment]
also i think @steffen12 we need birthdate to ensure workers/admins etc are older than 18 bc i dont think theyre authorized under HIPAA if theyre too young.
