### ISSUE TITLE
In AdminPanel, transfer use of UploadDocs to MyDocuments.tsx

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_client#69]
Instead of using UploadDocs, use MyDocuments (and similarly transfer everywhere else).

**Comment by loafyyy** [comment]
@steffen12 @crchong1 @scye09 could one of you clarify what the differences are, if any, between the MyDocuments page for client vs admin? After that, I can work on this issue.

**Comment by steffen12** [comment]
The MyDocuments page for admin should show the forms that are uploaded for client (there should be two - one for the blank forms and one for the completed applications, and right now we just have the completed applications). We want to eliminate the use of UploadDocs in general
