### ISSUE TITLE
Login Sometimes Does Not Log In

### ISSUE THREAD

**Issue by JohnBaek-wr** [keepid/keepid_client#73]
![image](https://user-images.githubusercontent.com/65623389/96274337-61809c00-0f9e-11eb-9183-7a0aca347936.png)

Sometimes when you click Sign In, nothing happens or maybe it's taking a while to load, possibly could be affected by cookies because when I allow cookies sometimes it works

**Comment by JohnBaek-wr** [comment]
Update, it logged in, so the bug is that it takes a while (might not be a bug)

**Comment by crchong1** [comment]
yeah sometimes it takes a while. We will look into making this process faster
