### ISSUE TITLE
Merge Master into VentureLab Branch

### ISSUE THREAD

**Issue by steffen12** [keepid/keepid_client#76]
We need to merge the new master into the VentureLab branch so that they can use the website, and we need the url venturelab.keep.id to work ASAP because we are beta testing with them soon, and we would like to collect funding.

**Comment by crchong1** [comment]
this might take a long time....

**Comment by crchong1** [comment]
@MelindaCardenas after you finish PFP can you look into this?

I am thinking that in the future, we use an internationalization software to swap out the words easily
