### ISSUE TITLE
Invalid State in My Account Settings page

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#78]
Invalid State error on My Account Settings page for clients. Either the state should be removed from this list or form validation should be fixed.

![image](https://user-images.githubusercontent.com/28871950/96319842-c0660580-0fde-11eb-8a71-41f7a3f8a0d7.png)

**Comment by scye09** [comment]
Oh or maybe it's supposed to be "MD" for Maryland?

**Comment by crchong1** [comment]
@scye09 yeah i think MP is not a valid state abbreviation. We should have a better pop up for that though

**Comment by vanessa-hu** [comment]
I think front-end includes Northern Mariana Islands (MP) and other territories as US states but backend validation doesn't acc for anything outside the 50 states. could remove from front-end json for now?

**Comment by crchong1** [comment]
yeah lets remove those - lol i didn't know that the front end had Northern Mariana Islands lol
