### ISSUE TITLE
Make changes to application footer

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#81]
- Page numbers don't change when moving on to next page
- "Previous step" button should not be on the first page
- Get rid of "Submit Form Answers" button - users should click "Continue" button instead

![image](https://user-images.githubusercontent.com/28871950/96325262-6a03c180-0ff4-11eb-9383-156bd6978e1e.png)

**Comment by crchong1** [comment]
@MelindaCardenas do you think you could look into this issue?

**Comment by MelindaCardenas** [comment]
yes! will look at it today/tomorrow
