### ISSUE TITLE
Organization sign up password validity indication doesn't change until you click away

### ISSUE THREAD

**Issue by jonathanxuexue** [keepid/keepid_client#82]
<img width="835" alt="Screen Shot 2020-10-18 at 2 57 37 PM" src="https://user-images.githubusercontent.com/59134039/96386853-ec09fc80-1152-11eb-9f9c-70f0240ee6d8.png">

**Comment by crchong1** [comment]
This is actually an interesting discussion to be had... so the reason the current implementation is there is bc it is a bit distracting to be constantly be hit with red while you are typing your password, so we made it so if you click away or if you submit the form the validation will check the field. @scye09 do you have thoughts on this?

**Comment by scye09** [comment]
I personally think that it's fine if we keep it as is (validating only after clicking/tabbing away) because it can be distracting while you're typing. I've also read articles saying that users fill out forms faster when inline validation happens after leaving the form field.
