### ISSUE TITLE
Organization sign up website shows invalid when it isn't – can't progress because of this issue

### ISSUE THREAD

**Issue by jonathanxuexue** [keepid/keepid_client#83]
<img width="1022" alt="Screen Shot 2020-10-18 at 2 59 15 PM" src="https://user-images.githubusercontent.com/59134039/96386862-fe843600-1152-11eb-846e-8037162ff094.png">

**Comment by crchong1** [comment]
@joeyszhao shouldn't your code add a https://www. to the front of keep.id? This should make the url valid? Or can you also check the regex
