### ISSUE TITLE
Worker actions for clients needs work

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#93]

**Comment by crchong1** [comment]
Login: testDirector2 for username and password
On client landing page, scroll down to Connor Chong
and click Upload Document
The username and password is testClient12

**Comment by crchong1** [comment]
@kofmangregory the problem is that when we click upload document, the document is no where to be seen when we login to the client account under testClient12 as username and password

**Comment by crchong1** [comment]
and im monitoring the server and it seems like it isn't even uploading the pdf to the backend

**Comment by loafyyy** [comment]
Is this still a problem @crchong1? If so, I can investigate.
